---
- name: Налаштування спільних компонентів
  hosts: all
  become: yes
  roles:
    - common

- name: Налаштування бази даних
  hosts: db
  become: yes
  roles:
    - database

- name: Налаштування додатку
  hosts: workers
  become: yes
  roles:
    - app