Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define "runner" do |runner|
    runner.vm.hostname = "runner-node"
    runner.vm.network "private_network", ip: "192.168.56.10"
    
    runner.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "devops_runner_vm"
    end
    
    runner.vm.provision "shell", path: "setup-runner.sh"
  end
end